[package]
name = "quine_macro"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["closure_macro"]

[dependencies]
closure_macro = {path = "closure_macro"}

[dev-dependencies]
pretty_assertions = "1.4.0"
